### PR TITLE
Fixed the URL of the compiled ES Module

### PR DESCRIPTION
**Pull request by baocang**
- [ ] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by baocang** [comment]
Fixed https://github.com/Polymer/polymer-cli/issues/894

**Comment by baocang** [comment]
@usergenic Can you help me review it, That blocks polymer serve --npm --compile always, Thanks!

**Comment by usergenic** [comment]
@baocang I'm going to merge into a local branch to try out changes.  Thanks for the PR!

**Comment by baocang** [comment]
@usergenic Thanks

When I run `polymer serve --npm --compile alwasy`, I get the below error:
```GET http://127.0.0.1:8081/hrlink-route.js net::ERR_ABORTED```.

Because inside ```http://127.0.0.1:8081/node_modules/hrlink-route/hrlink-route.html```,
the ```<script type="module" src="hrlink-route.js"></script>```
is compiled to ```<script>require(["hrlink-route.js"]);</script>```,
there right will be ```<script>require(["/node_modules/hrlink-route/hrlink-route.js"]);</script>```
or compile resolved path of```hrlink-route.js``` into ```requirejs.config.paths```, the mostly easy way is just resolve the url for  ```<script type="module" src="hrlink-route.js"></script>```.

Thanks again.

**Comment by baocang** [comment]
Anybody deal with this problem?

**Pull request merged**
