### PR TITLE
Honor .bowerrc setting for componentDir

### LINKED ISSUE #27: Read directory from .bowerrc
The .bowerrc file allows you to override your bower directory. The script should default to the configured directory.

### PR DESCRIPTION
**Pull request by redbugz**
Reads directory from .bowerrc if available, but defaults to bower_components for both initial config and variants
Fixes #27 and helps with Polymer/web-component-tester#488

- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by justinfagnani** [comment]
@redbugz thanks for the PR! Looks good, but can we get a rebase?

**Comment by redbugz** [comment]
@justinfagnani I have the PR back up to date, but it's gotten a bit messy in the history. Do you clean that up on merge with a squash or similar, or do you need me to do some cleanup?

**Comment by web-padawan** [comment]
@regbugz I'd rather do a rebase as @justin suggested, with a soft reset to collaspe changes in one commit.

Friday picture: 
git

**Comment by redbugz** [comment]
I believe I have it properly rebased now. @justinfagnani

**Comment by web-padawan** [comment]
@justinfagnani could you review and merge this please once you have time after the Summit?

**Comment by web-padawan** [comment]
A gentle ping on this to @usergenic

**Comment by justinfagnani** [comment]
@web-padawan doing this now

**Comment by justinfagnani** [comment]
This failed only due to a new version of node coming out. Test pass otherwise.

**Pull request merged**
